import uuid
from sqlalchemy import Column, Integer, String, Float, ARRAY, ForeignKey, DateTime
from sqlalchemy.orm import relationship
from db.models.base import Base

class Listing(Base):
    __tablename__ = 'listings'
    
    id =  Column(String(36), primary_key=True, default= lambda: str(uuid.uuid4()))
    listing_url =  Column(String, nullable=False)
    name =  Column(String)
    description =  Column(String)
    neighborhood_overview = Column(String)
    picture_url =  Column(String)
    neighbourhood =  Column(String)
    latitude =  Column(Float)
    longitude = Column(Float)
    property_type =  Column(String)
    room_type =  Column(String)
    accommodates =  Column(Integer)
    bathrooms = Column(Float)
    bathrooms_text =  Column(String)
    bedrooms =  Column(Float)
    beds =  Column(Float)
    price_USD =  Column(Float)
    minimum_nights = Column(Integer)
    maximum_nights =  Column(Integer)
    minimum_nights_avg_ntm =  Column(Float)
    maximum_nights_avg_ntm = Column(Float)
    has_availability =  Column(String)
    availability_30 =  Column(Integer)
    availability_60 = Column(Integer)
    availability_90 =  Column(Integer)
    availability_365 =  Column(Integer)
    number_of_reviews = Column(Integer)
    first_review =  Column(DateTime)
    last_review =  Column(DateTime)
    review_scores_rating = Column(Integer)
    instant_bookable =  Column(String)
    calculated_host_listings_count = Column(Integer)
    calculated_host_listings_count_entire_homes = Column(Integer)
    calculated_host_listings_count_private_rooms = Column(Integer)
    calculated_host_listings_count_shared_rooms =  Column(Integer)
    reviews_per_month = Column(Float)
    host_id =  Column(String(36), ForeignKey('hosts.id'), nullable=False)
    price_BRL =  Column(Float)
    price_category =  Column(String)
    first_review_filled = Column(DateTime)
    never_reviewd = Column(Integer)
    
    host = relationship('Host', back_populates='listings')