services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ../config/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 10s
      retries: 5
      timeout: 5s

  airflow-webserver:
    image: apache/airflow:latest
    container_name: airflow-webserver
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ../config/.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./configs/airflow.cfg:/opt/airflow/airflow.cfg
    command: >
      bash -c "airflow webserver"
    ports:
      - "8080:8080"

  airflow-scheduler:
    image: apache/airflow:latest
    container_name: airflow-scheduler
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ../config/.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./configs/airflow.cfg:/opt/airflow/airflow.cfg
    command: >
      bash -c "airflow scheduler"

volumes:
  postgres_data: